#!/bin/bash
set -e

file="$1"
[[ -n "$file" ]] || exit 1
shift
dir="$(dirname "$file")"
filename="$(basename "$file")"
exe="$dir/bin/${filename/.cpp/}"

[[ -d "$dir/bin" ]] || mkdir "$dir/bin"

g++ -std=c++20 "$file" -o "$exe" "$@"

# Return compile executable path
echo "$exe"
